# Generated by Django 5.2.7 on 2025-10-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_of_birth'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
