# Generated by Django 5.2.7 on 2025-10-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['established_date'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='bankbranch',
            options={'ordering': ['name'], 'verbose_name': 'Branch Branch', 'verbose_name_plural': 'Branch Branches'},
        ),
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
        migrations.AlterModelTable(
            name='bankbranch',
            table='branch',
        ),
    ]
