# Generated by Django 5.2.7 on 2025-10-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVING', 'Saving')], default='CURRENT')),
                ('balance', models.PositiveIntegerField(max_length=11)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='banks.bankbranch')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'ordering': ['balance'],
            },
        ),
    ]
