# Generated by Django 5.2.7 on 2025-10-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVING', 'Saving')], default='CURRENT')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='banks.bankbranch')),
            ],
        ),
    ]
