# Generated by Django 5.2.7 on 2025-10-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['balance'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.PositiveIntegerField(max_length=11),
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_accounts',
        ),
    ]
